name: Docker Image CI

on:
    pull_request:
      branches:
        - dev_python
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: bash docker/build/build.sh
