name: Docker Image CI

on:
    push:
      branches:
        - dev_python
    pull_request:
      branches:
        - dev_python

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule foreach --recursive git fetch
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --recursive
    - name: Build the Docker image
      run: docker build --build-arg http_proxy=192.168.1.11:8118 --build-arg https_proxy=192.168.1.11:8118 --rm -t oneflow-build -f docker/build/Dockerfile .

