name: Docker Image CI

on:
    push:
      branches:
        - dev_python
    pull_request:
      branches:
        - dev_python

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        echo "${GITHUB_TOKEN}"
        auth_header="AUTHORIZATION: basic ${GITHUB_TOKEN}"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build the Docker image
      run: bash docker/build/build.sh
